import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import { UserProvider } from '@auth0/nextjs-auth0/client';

const jost = Jost({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Home App V2',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={jost.className}>
          <div className='flex bg-[#F5F5F5]'>
            <Sidebar />
            {children}
          </div>
        </body>
      </html>
    </UserProvider> 
  );
}
